[package]
name = "monkey-rust"
version = "0.0.0"
authors = ["masaki.ono <aaikmnoos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
